server:
  port: 3000
spring:
  security:
    user:
      name: caco
      password: caco123
  application:
    name: caco-eureka
  profiles:
    active: dev

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://caco:caco123@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 4000
    enable-self-preservation: false
    renewal-percent-threshold: 0.9

management:
  endpoints:
    web:
      exposure:
        exclude: '*'
