server:
  port: 8080

spring:
  application:
    name: caco-gateway
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://caco:caco123@127.0.0.1:3000/eureka/
